version: '3.4'

services:
  notdown:
    image: notdown:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    container_name: down
    networks:
      - ndown

networks:
  ndown:
    driver: bridge
